version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env

  redis:
    image: redis:5.0-alpine
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

  app:
    build: .
    command: bash -c "bundle exec sidekiq -d -L log/sidekiq.log && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/chat_system"
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env