default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_ROOT_USER'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
